### ISSUE TITLE
Download status is always "Started", it doesn't update correctly. #1098

### ISSUE THREAD

**Issue by 1lluzi0nzz** [MSU-CS4360-Nuclear/nuclear#22]
Even when the song is downloaded, it shows it as "Started" and because of that, clear finished tracks doesn't work as well

@JFMugen added the bug label 8 days ago

1lluzi0nzz - 
nukeop, would adding a localized 'Downloading' & 'Completed' status resolve this issue? If so, can I have this issue?
 
nukeop -
There already is a status for this, but it's updated incorrectly

1lluzi0nzz - 
Ah, I see there are already a few statuses now. Can I take this?

**Comment by 1lluzi0nzz** [comment]
This is resolved in our downloads branch.

**Comment by jreiser1** [comment]
Nice work, should we open a pull request to the main project?
