### ISSUE TITLE
Sort tracks in Favorite Tracks page 

### ISSUE THREAD

**Issue by jreiser1** [MSU-CS4360-Nuclear/nuclear#24]
Duplicate of https://github.com/nukeop/nuclear/issues/722
User should be able to sort Favorite tracks alphabetically (or reverse alphabetical order) either by track name or artist name.
![image](https://user-images.githubusercontent.com/47801590/146101559-69ced822-ce3c-4832-b2c5-f48a4458efc0.png)

We could toggle the sorting by clicking on these two labels.

**Comment by jreiser1** [comment]
Tracks can now be sorted in standard or reverse alphabetical order by artist or track name
![image](https://user-images.githubusercontent.com/47801590/146129518-6b0c2006-8bea-4692-b7a4-dc9655007c6d.png)
![image](https://user-images.githubusercontent.com/47801590/146129564-86639e77-8a85-4944-84fb-4db0e7e572da.png)
![image](https://user-images.githubusercontent.com/47801590/146129542-9ea93756-079c-4ecb-a647-8e5ce0f81b48.png)
![image](https://user-images.githubusercontent.com/47801590/146129587-59c7d5c2-152d-401e-aebc-8209c57c2761.png)

**Comment by 1lluzi0nzz** [comment]
Tried fixing the snapshot test for the FavoritesContainer for awhile, pretty much out of ideas.  For whatever reason the snapshot produce an empty list where we expect to see a list of test Artists.

**Comment by jreiser1** [comment]
Pull request merged into master
