### ISSUE TITLE
Taskbar Icon not rendering correctly/completely

### ISSUE THREAD

**Issue by jreiser1** [MSU-CS4360-Nuclear/nuclear#4]
Platform: Windows 10 Ver. 2004 Build 19041.1165

Nuclear version: 0.6.16

Description of the issue: The Logo/Icon of Nuclear is not rendering properly in the taskbar, as only the top most slither of it is rendered, and the rest is blank space. I've stumbled upon this Issue in previous versions and it doesn't depend on whether I've downloaded Nuclear through winget or directly from the [site/github.]

A link to a screenshot
(https://i.imgur.com/ts9iMu2.png)

**Comment by 1lluzi0nzz** [comment]
Gonna start taking a look at this one, have the production build installed from Snap.

**Comment by 1lluzi0nzz** [comment]
Believe I have a fix.  Will commit it shortly, but it should address both Nuclear issues #1044 & #1007.  Issue was an odd presentation of pathing issues.

**Comment by jreiser1** [comment]
fixed
